### ISSUE TITLE
Login to the app using Auth0

### ISSUE THREAD

**Issue by vertis** [graphql360/dtour-ios#2]
We're using Auth0 for the Authentication. A quick start here: https://auth0.com/docs/quickstart/native/ios-swift/00-login

The settings you will need:
Domain: graphql360.auth0.com
Client Id: FL3qAI7rqaJfXeKQ2Rhb8Vjg5GhqlZgV

**Comment by rostyslav-gryb** [comment]
In order to make the login work we need to add the callback url `com.graphql360.capture.alpha://graphql360.auth0.com/ios/com.graphql360.capture.alpha/callback` to the **Allowed Callback URLs** on the Auth0 portal. Currently we use bundle identifier `com.graphql360.capture.alpha` for initial development stage. We can change it later closer to the finalization.
